### ISSUE TITLE
Check for uppercase characters when using the `i` flag

### ISSUE THREAD

**Issue by theseion** [coreruleset/crs-toolchain#113]
When the `i` flag is used, the entire regular expression will be case insensitive and all upper case letters can be replaced by their lowercase counterparts.

**Comment by fzipi** [comment]
Started playing with this. Some caveats:
- this doesn't work out of the box. Examples: `[Aa]sdf`, or `[A-Jl-m]`.

What I thought is just emit a warning like:
```
{"level":"warn","component":"parser","time":"2024-02-26T14:08:19-03:00","message":"File contains uppercase letters, but ignore-case flag is set. Please check your source files."}
{"level":"warn","component":"parser","time":"2024-02-26T14:08:19-03:00","message":"File content matched around char 50: another regex\n{1,3}[Bb]lah\n"}
```

**Comment by fzipi** [comment]
@theseion ☝️

**Comment by theseion** [comment]
Pretty much what I thought to do. I'd also add it to the format checker so we can run it as a lint rule on GH.

What are you trying to match? IMO, we simply check whether the `.ra` file sets the `i` flag, and then find the first index of an upper case letter. I think we can ignore hex escapes, etc. and just focus on ASCII.

**Comment by fzipi360** [comment]
Excellent. That was my idea, so we are in sync now 😄.
