### ISSUE TITLE
Add automation for updating copyright information

### ISSUE THREAD

**Issue by theseion** [coreruleset/crs-toolchain#27]
CRS has the year written on its copyright information on every rules file. So each new year we need to be able to update it easily.

**Requirements**
- go over each rule file and update the year. An example could be:
```
# OWASP ModSecurity Core Rule Set ver.4.0.0-rc1
# Copyright (c) 2006-2020 Trustwave and contributors. All rights reserved.
# Copyright (c) 2021-2022 Core Rule Set project. All rights reserved.
```
Should change, next year to:
```
# OWASP ModSecurity Core Rule Set ver.4.0.0-rc1
# Copyright (c) 2006-2020 Trustwave and contributors. All rights reserved.
# Copyright (c) 2021-2023 Core Rule Set project. All rights reserved.
```

**Output**
- a new command (or option) to do this. If we think that this is part of a list of _chores_ we will be doing for the CRS, the `crs-toolchain chore copyright-update` might work?

**Comment by fzipi** [comment]
Maybe this helps: https://cs.opensource.google/go/x/tools/+/master:copyright/copyright.go
