### ISSUE TITLE
Automate creating new branches for major releases

### ISSUE THREAD

**Issue by theseion** [coreruleset/crs-toolchain#29]
- After creating the new branches, update the version in the new branches to the new version.
- Set the new dev branch as the default branch on GitHub
- Set branch protections on new branch
- Update nightly workflow to use the new branch
- update version in contributing.md
- update version info in *.conf files and rule files

**Comment by fzipi** [comment]
Now that we have `main`, is this necessary?

**Comment by theseion** [comment]
The last two points remain, but that's obvious.
