### ISSUE TITLE
Implement data file linter

### ISSUE THREAD

**Issue by theseion** [coreruleset/crs-toolchain#32]
...TBF?

**Comment by fzipi** [comment]
@theseion Do you have more context on what goes here?

**Comment by theseion** [comment]
I think this is out of scope. I was thinking of ways to give hints to users. Examples:
- "Use `\x5c` instead of backslash`"
- "Place dash character at the end of character class to avoid confusion with the range operator"
- "This block of 5 lines is repeated <n> times. Use `assemble` to store the resulting expression for reuse instead"

Unfortunately, most of these become very complicated very quickly. We have the formatter for now and we know whether the content is valid.
