### ISSUE TITLE
Caller entry in log should not include path

### ISSUE THREAD

**Issue by theseion** [coreruleset/crs-toolchain#50]
Currently, when running the toolchain, the caller entry in the log is printed with the relative path to the module:

```
02:26:28 INF ../../../go/pkg/mod/github.com/coreruleset/crs-toolchain/v2@v2.0.0-20221119080758-c264fb6b6ed6/cmd/regex_format.go:132 > Formatting url-schemes.data component=cmd
```

`regex_format.go:132` is enough, the path information is just noise.

**Comment by fzipi** [comment]
This is fixed now.
