### ISSUE TITLE
Enforce that include files must be written with case-sensitivity in mind (flags are not supported)

### ISSUE THREAD

**Issue by theseion** [coreruleset/crs-toolchain#72]
As detailed in #71, it is not possible to support PCRE compatible flags in include files due to issues with `rassemble-go` and `regexp/syntax`. In order to ensure that include files retain semantics (not fully possible, strictly speaking, but should be good enough), regardless of the flags defined in the including file, it is necessary to:
- [x] remove special flag handling for include files from the toolchain (`mergeFlagsPrefixesSuffixes` in `parser.go`)
- [x] validate and update all existing include files, such that flags are replaced with other means to achieve the same semantics
- [x] enforce that include files do not contain flags by adding a step to the toolchain linter
- [x] update all rule expressions

**Comment by dune73** [comment]
Is there any chance this will be fixed in upstream - ever?

**Comment by fzipi** [comment]
> * validate and update all existing include files, such that flags are replaced with other means to achieve the same semantics

From what I see in the [include files](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/regex-assembly/include), there are no flags. So this should be good.

**Comment by theseion** [comment]
That's good but we also need to make sure that the include files can be used if the including file doesn't have an `i` flag. For example, the charset include file should have `[uU][tT][fF]-8` instead of `utf-8`.

**Comment by theseion** [comment]
Or maybe it's enough and we just presume that everybody knows what they are doing. I'm not sure... Adding that much to the include files also sucks...

**Comment by fzipi** [comment]
I think we should add documentation about it, but not add it to the files.

We mostly use the case insensitive option all over regexes.

**Comment by fzipi** [comment]
Why not just exit with Fatal if we find a flag in an included file? That would work for both cases, but also will ensure that no file has it.

**Comment by theseion** [comment]
You're right. That would actually be better because the presence of the flag is actually an error in this case.

**Comment by dune73** [comment]
I favor hard break too.

**Comment by fzipi** [comment]
We need to release probably, but this is done.
